import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ConvexClientProvider from "./ConvexClientProvider";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import CameraDevicesProvider from "@/providers/CameraDevicesProvider";
const inter = Inter({ subsets: ["latin"] });

export const runtime = "edge";

export const metadata: Metadata = {
  title: "Next.js + Convex",
  description: "Generated by create next app and using Convex",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider><ThemeProvider attribute="class" defaultTheme="system">
        <CameraDevicesProvider>{children}</CameraDevicesProvider>
                    <Toaster />
                </ThemeProvider>
                </ConvexClientProvider>
      </body>
    </html>
  );
}
